{% set name = "base64io" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24f2d0fe765c35339e1b2d33aa95f9137b1b765b594164fad1016c15827a7073

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.1,<4.0.0
  run:
    - python >=3.7.1,<4.0.0

test:
  imports:
    - base64io
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aws/base64io-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A streaming interface for Base64 encoding

extra:
  recipe-maintainers:
    - mands
